package com.grupo4.recordatoriosmedicamentos.core

import com.grupo4.recordatoriosmedicamentos.data.network.entities.fda.Product

object Constants {
    const val USER_ID = "id"
    const val TAG = "UCE"
    val products = listOf(
        Product("FOSINOPRIL SODIUM AND HYDROCHLOROTHIAZIDE"),
        Product("DIPHENHYDRAMINE HYDROCHLORIDE"),
        Product("TIZANIDINE HYDROCHLORIDE"),
        Product("CIPROFLOXACIN HYDROCHLORIDE"),
        Product("MESALAMINE"),
        Product("RIVASTIGMINE TARTRATE"),
        Product("PAMIDRONATE DISODIUM"),
        Product("LOSARTAN POTASSIUM AND HYDROCHLOROTHIAZIDE"),
        Product("STAVUDINE"),
        Product("NICOTINE POLACRILEX"),
        Product("LETROZOLE"),
        Product("SULFINPYRAZONE"),
        Product("CHORIONIC GONADOTROPIN"),
        Product("HYDROCORTISONE"),
        Product("PREDNISOLONE SODIUM PHOSPHATE"),
        Product("METHYLPREDNISOLONE SODIUM SUCCINATE"),
        Product("DIPHENHYDRAMINE HYDROCHLORIDE"),
        Product("RESERPINE"),
        Product("MYCELEX-7"),
        Product("PHENDIMETRAZINE TARTRATE"),
        Product("ISOLYTE E W/ DEXTROSE 5% IN PLASTIC CONTAINER"),
        Product("TYZINE"),
        Product("DIPHENOXYLATE HYDROCHLORIDE AND ATROPINE SULFATE"),
        Product("TRIFLUOPERAZINE HYDROCHLORIDE"),
        Product("DISULFIRAM"),
        Product("LIDOCAINE HYDROCHLORIDE IN PLASTIC CONTAINER"),
        Product("BUTABARBITAL SODIUM"),
        Product("MONTELUKAST SODIUM"),
        Product("CALCITRIOL"),
        Product("METFORMIN HYDROCHLORIDE"),
        Product("ABACAVIR SULFATE; LAMIVUDINE"),
        Product("IBANDRONATE SODIUM"),
        Product("DONEPEZIL HYDROCHLORIDE"),
        Product("DIPHENHYDRAMINE HYDROCHLORIDE PRESERVATIVE FREE"),
        Product("PORTRAZZA"),
        Product("ETHOSUXIMIDE"),
        Product("FAMOTIDINE"),
        Product("TRETINOIN"),
        Product("HYDROCHLOROTHIAZIDE"),
        Product("LINAGLIPTIN; METFORMIN HYDROCHLORIDE"),
        Product("AIRDUO DIGIHALER"),
        Product("IBUPROFEN"),
        Product("ROGAINE (FOR WOMEN)"),
        Product("JYNARQUE"),
        Product("POSIMIR"),
        Product("HYDROCODONE BITARTRATE), CHLORPHENIRAMINE MALEATE AND PSEUDOEPHEDRINE HYDROCHLORIDE"),
        Product("PRASUGREL"),
        Product("CLOZAPINE"),
        Product("TIAGABINE HYDROCHLORIDE"),
        Product("MEMANTINE HYDROCHLORIDE"),
        Product("IBUPROFEN"),
        Product("CHILDRENS IBUPROFEN"),
    )
}